/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "and_gate.v:1.1-3.10" *)
module and_gate(a, b, y);
  (* src = "and_gate.v:1.23-1.24" *)
  input a;
  wire a;
  (* src = "and_gate.v:1.32-1.33" *)
  input b;
  wire b;
  (* src = "and_gate.v:1.42-1.43" *)
  output y;
  wire y;
  sky130_fd_sc_hd__and2_0 _0_ (
    .A(a),
    .B(b),
    .X(y)
  );
endmodule
