/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module alu(a, b, sel, result);
  wire _0_;
  wire _1_;
  wire _2_;
  input [1:0] a;
  wire [1:0] a;
  input [1:0] b;
  wire [1:0] b;
  output [1:0] result;
  wire [1:0] result;
  input sel;
  wire sel;
  sky130_fd_sc_hd__xor2_1 _3_ (
    .A(sel),
    .B(a[0]),
    .X(_1_)
  );
  sky130_fd_sc_hd__nand2_1 _4_ (
    .A(b[0]),
    .B(_1_),
    .Y(_2_)
  );
  sky130_fd_sc_hd__xor2_1 _5_ (
    .A(b[1]),
    .B(a[1]),
    .X(_0_)
  );
  sky130_fd_sc_hd__xnor2_1 _6_ (
    .A(_2_),
    .B(_0_),
    .Y(result[1])
  );
  sky130_fd_sc_hd__xor2_1 _7_ (
    .A(b[0]),
    .B(a[0]),
    .X(result[0])
  );
endmodule

module counter(clk, rst, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  input clk;
  wire clk;
  output [3:0] count;
  wire [3:0] count;
  input rst;
  wire rst;
  sky130_fd_sc_hd__nor2_1 _08_ (
    .A(rst),
    .B(count[0]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__xnor2_1 _09_ (
    .A(count[0]),
    .B(count[1]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nor2_1 _10_ (
    .A(rst),
    .B(_04_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__and3_1 _11_ (
    .A(count[0]),
    .B(count[1]),
    .C(count[2]),
    .X(_05_)
  );
  sky130_fd_sc_hd__a21oi_1 _12_ (
    .A1(count[0]),
    .A2(count[1]),
    .B1(count[2]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__nor3_1 _13_ (
    .A(rst),
    .B(_05_),
    .C(_06_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__xnor2_1 _14_ (
    .A(count[3]),
    .B(_05_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nor2_1 _15_ (
    .A(rst),
    .B(_07_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__dfxtp_1 _16_ (
    .CLK(clk),
    .D(_00_),
    .Q(count[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _17_ (
    .CLK(clk),
    .D(_01_),
    .Q(count[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _18_ (
    .CLK(clk),
    .D(_02_),
    .Q(count[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _19_ (
    .CLK(clk),
    .D(_03_),
    .Q(count[3])
  );
endmodule

module mini_soc(clk, rst, alu_sel, mux_sel, soc_out);
  wire [1:0] alu_out;
  input alu_sel;
  wire alu_sel;
  input clk;
  wire clk;
  wire [3:0] count;
  input mux_sel;
  wire mux_sel;
  input rst;
  wire rst;
  output [1:0] soc_out;
  wire [1:0] soc_out;
  alu u_alu (
    .a(count[3:2]),
    .b(count[1:0]),
    .result(alu_out),
    .sel(alu_sel)
  );
  counter u_counter (
    .clk(clk),
    .count(count),
    .rst(rst)
  );
  mux2x1 u_mux (
    .in0(count[3:2]),
    .in1(alu_out),
    .out(soc_out),
    .sel(mux_sel)
  );
endmodule

module mux2x1(in0, in1, sel, out);
  input [1:0] in0;
  wire [1:0] in0;
  input [1:0] in1;
  wire [1:0] in1;
  output [1:0] out;
  wire [1:0] out;
  input sel;
  wire sel;
  sky130_fd_sc_hd__mux2_1 _0_ (
    .A0(in0[0]),
    .A1(in1[0]),
    .S(sel),
    .X(out[0])
  );
  sky130_fd_sc_hd__mux2_1 _1_ (
    .A0(in0[1]),
    .A1(in1[1]),
    .S(sel),
    .X(out[1])
  );
endmodule
